
---
- name: Configure App
  hosts: app
  gather_facts: no
  become: true

  vars:
    # db_host: 158.160.36.89    # use 'internal_ip_address_db' for static inventory
    # db_host: "{{ hostvars['dbserver']['ansible_all_ipv4_addresses'][0] }}"    # use for ./yc-inventory.py
    db_host: "{{ hostvars['fhmnvh10jbu0u2utd6ao.auto.internal']['ansible_all_ipv4_addresses'][0] }}" # use for./yc_compute.yml
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable puma
      systemd:
        name: puma
        enabled: yes
      tags: app-tag

  handlers:
    - name: reload puma
      systemd:
        name: puma
        state: restarted