---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  gather_facts: no
  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted

- name: Configure App
  hosts: app
  tags: app-tag
  become: true
  gather_facts: no
  vars:
    db_host: 10.128.0.3

  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable puma
      systemd:
        name: puma
        enabled: yes
      tags: app-tag

  handlers:
    - name: reload puma
      systemd:
        name: puma
        state: restarted

- name: Deploy application
  hosts: app
  tags: deploy-tag
  gather_facts: no

  tasks:
    - name: Install git
      become: true
      apt:
        state: present
        name: git>=1.7.1

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
    - name: reload puma
      become: true
      systemd:
        name: puma
        state: restarted
